version: "3"

services:

  technical-data:
    build: ./
    restart: always
    volumes:
      - ./:/project/
    ports:
      - 2323:2323  #localPort:containerPort
    #stdin_open: true
    tty: true
    image: coinmove/technical-data:13.6.21
